sudo: false
language: node_js

node_js:
  - "6.10.2"
  - "stable"

cache: yarn

addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
    - /

script:
  - "npm run lint"
  - "npm test"
  - "./deploy.sh"

matrix:
  allow_failures:
    - node_js: "stable"
