sudo: false

language: node_js

node_js:
  - 6.10.2
  - node

cache: yarn

before_install:
  - if [[ `npm -v` != 4* ]]; then node ./yarn-0.25.3.js global add npm@4; fi

install:
  - node ./yarn-0.25.3.js install --frozen-lockfile

addons:
  artifacts:
    s3_region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /

script:
  - node ./yarn-0.25.3.js lint
  - node ./yarn-0.25.3.js test
  - ./artifact.sh

matrix:
  allow_failures:
    - node_js: node

notifications:
  email:
    on_success: change
    on_failure: always
